# Generated by Django 5.2.17 on 2026-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_submission_submissionimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('checking', 'Checking'), ('checked', 'Checked'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
