# Generated by Django 5.2.17 on 2026-08-07 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_submission_status'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='library.book'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='extracted_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='page_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='page_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
