# Generated by Django 5.2.17 on 2026-08-06 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0003_alter_submission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('mistakes', models.JSONField(default=list)),
                ('feedback', models.TextField(default='')),
                ('ai_model', models.CharField(max_length=50)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_result', to='assignments.submission')),
            ],
            options={
                'verbose_name': 'Check Result',
                'verbose_name_plural': 'Check Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
